name: My First workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome messege
          run: echo "Welcome to actions"
        
        - name: List files
          run: ls

        - name: read files
          run: cat README.md
