name: My First workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v7

        - name: Welcome messege
          run: |
            echo "Welcome to actions"
            ls -ltra
            cat README.md
          