name: Generate ASCI

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v7

        - name: Install cowsay library
          run: sudo apt-get install cowsay -y

        - name: Create dragon.txt
          run: cowsay -f dragon "Run for cover. I am DRAGON.RAWR...." >> dragon.txt

        - name: Display ASCI artwork\
          run: cat dragon.txt

        - name: List files\
          run: ls -ltra