name: Variables and secrets

on: push
env:
  CONTAINER-Registry: docker.io
  image-name: github-action-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: docker build
      echo docker build -t ${{env.CONTAINER-Registry}}/{{vars.Docker_username}}/$image-name

    - name: docker login
      echo docker build -t ${{env.CONTAINER-Registry}}/${{vars.Docker_username}}/${{vars.DOCKER_PW}}